<a href="https://colab.research.google.com/github/marlaudurtizberea/demo-repo2/blob/master/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

Ressource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Checking the dimension of a tensor
scalar.ndim

0

In [ ]:
# Get the Python number within a tensor (only works with one-element tensor)
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Check the number of dimensions of vector
vector.ndim

1

The dimension of an object is the number of square brackets []
Our vector here as only 1 set of square bracket and so is of dimension 1

In [ ]:
# Check the shape of vector
vector.shape

torch.Size([2])

So there is two elements inside the saqure brackets

In [ ]:
# MAtrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Check the number of dimensions
print("dimension of MATRIX : ",MATRIX.ndim)
print(MATRIX.shape)

dimension of MATRIX :  2
torch.Size([2, 2])


In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# Check the number of dimension for TENSOR
TENSOR.ndim

3

In [ ]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

That means there's 1 dimension of 3 by 3

In [ ]:
# Practice with different tensor shape
TENSOR = torch.tensor([[[1,2,3,4],
                        [3,4,5,6]],
                       [[3,4,5,6],
                        [7,8,9,10]]])
print(TENSOR)
print(TENSOR.shape)

tensor([[[ 1,  2,  3,  4],
         [ 3,  4,  5,  6]],

        [[ 3,  4,  5,  6],
         [ 7,  8,  9, 10]]])
torch.Size([2, 2, 4])


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2448, 0.2215, 0.0545, 0.9709],
         [0.4037, 0.6651, 0.0206, 0.7072],
         [0.3474, 0.8364, 0.0159, 0.8348]]),
 torch.float32)

In [ ]:
# Create a random tensor of size (224,224,3)
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Creat a tensor of all ones
ones = torch.ones(size = (3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# Use torch arrange() to create a range of values 0 to 10
zero_to_ten = torch.arange(0,10,1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input = zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor data type

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
# Let's create a tensor float16
float_16_tensor = torch.tensor([3.0, 6.0,9.0],
                               dtype = torch.float16)
float_16_tensor.dtype

torch.float16

How to get information from tensors ?


    shape - what shape is the tensor? (some operations require specific shape rules)
    dtype - what datatype are the elements within the tensor stored in?
    device - what device is the tensor stored on? (usually GPU or CPU)


In [ ]:
# Example

#Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}")

tensor([[0.1390, 0.5073, 0.4577, 0.2466],
        [0.2882, 0.2858, 0.0205, 0.9591],
        [0.2982, 0.3671, 0.2560, 0.7160]])
Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


# Manipulating Tensor

## Basic operations

In [ ]:
# Creat a tensor of values and add a number to it
tensor = torch.tensor([1,2,3]) # Creating the tensor
tensor + 10 # Adding 10 to the tensor

tensor([11, 12, 13])

In [ ]:
# Multiply the tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Attention, tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [ ]:
# Substract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Built in function in PyTorch for multiplication and addition

In [ ]:
# Multiply
print(torch.multiply(tensor,10))

tensor([10, 20, 30])


In [ ]:
# Element-wise multiplication
print(tensor,"*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Matrix multiplication

In [ ]:
import torch
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

Analysing common error in deep learning  : shape erros

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape : {output.shape}")

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A.T
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Finding the min, max mean and sum

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x

In [ ]:
print(f"Minimum : { x.min()}")
print(f"Maximum : {x.max()}")
print(f"Mean : {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

In [ ]:
# Same as above with torch method

torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

Positional min/max

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Change tensor datatype

In [ ]:
# Create a tensor and check its dataype
tensor = torch.arange(10.,100.,10.)
tensor.dtype

In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

In [ ]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - Reshapes an iput tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking  - Combine multiple tensors on top of each other (vstack or side by side (hstack)
* Squeeze - Remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# We could aslo have done
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change view (keeps same data as orginal but changes view)
# See more : https://stackoverflow.com/a/54507446/7900723
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() removes all single dimensions from a targe tensor
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x_unsqueezed = x.unsqueeze(0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])
